[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/","@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]


[invariant]
runs = 128
depth = 128
fail_on_revert = true # if we want to narrow our search to break our invariant we set this to true else false 
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
